services:
  nginx:
    image: nginx:latest
    container_name: 'yidan-admin-nginx'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
      - ./certificates/localhost.pem:/etc/ssl/certificates/localhost.pem
      - ./certificates/localhost-key.pem:/etc/ssl/certificates/localhost-key.pem